apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: targylyen-nginx
  annotations:
    # notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-rollout-updated.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-rollout-completed.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-rollout-aborted.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-rollout-paused.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-analysis-run-failed.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-analysis-run-error.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-analysis-run-running.slack: notifications_targylyen
    # notifications.argoproj.io/subscribe.on-scaling-replica-set.slack: notifications_targylyen
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: targylyen-nginx
  template:
    metadata:
      labels:
        app: targylyen-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine-perl  # Replace with your image
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
      - command:
          - "/bin/sleep"
          - "infinity"
        image: busybox:latest
        name: busybox
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
